name: 🔍 PR Validation

on:
  pull_request:
    branches: [ main, master, develop ]
    types: [ opened, synchronize, reopened ]

# Permisos necesarios para que el workflow pueda acceder a la API de GitHub
permissions:
  contents: read          # Para leer el código del repositorio
  pull-requests: read     # Para leer información de pull requests
  issues: write          # Para crear y actualizar comentarios en PRs

# Cancelar workflows anteriores si se hace un nuevo push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-check:
    name: 🎯 Quality Check
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          # Necesario para que jscpd pueda comparar contra historial
          fetch-depth: 0

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            frontend/package-lock.json
            backend/package-lock.json
            shared/package-lock.json
            claude-cli/package-lock.json

      - name: 🔧 Install dependencies
        run: |
          npm ci
          npm run install:workspaces

      - name: 🧹 ESLint Check
        run: |
          echo "🔍 Ejecutando controles de ESLint..."
          npm run lint:complexity
        continue-on-error: false

      - name: 🔍 Duplicate Code Detection
        run: |
          echo "🔍 Detectando código duplicado..."
          npm run lint:duplicates
        continue-on-error: false

      - name: 📊 Generate Quality Report
        if: always()
        run: |
          echo "📊 Generando reporte de calidad..."
          npm run quality:report || true

      - name: 📋 Upload Quality Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: quality-reports
          path: quality-reports/
          retention-days: 7

  test-check:
    name: 🧪 Test Suite
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            frontend/package-lock.json
            backend/package-lock.json
            shared/package-lock.json
            claude-cli/package-lock.json

      - name: 🔧 Install dependencies
        run: |
          npm ci
          npm run install:workspaces

      - name: 🧪 Run Tests
        run: |
          echo "🧪 Ejecutando pruebas unitarias..."
          npm run test
        continue-on-error: false

  build-check:
    name: 🏗️ Build Verification
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            frontend/package-lock.json
            backend/package-lock.json
            shared/package-lock.json
            claude-cli/package-lock.json

      - name: 🔧 Install dependencies
        run: |
          npm ci
          npm run install:workspaces

      - name: 🏗️ Build Project
        run: |
          echo "🏗️ Construyendo proyecto..."
          npm run build
        continue-on-error: false

  pr-summary:
    name: 📝 PR Summary
    runs-on: ubuntu-latest
    needs: [quality-check, test-check, build-check]
    if: always()
    
    steps:
      - name: 📝 Create PR Summary
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            const qualityResult = '${{ needs.quality-check.result }}';
            const testResult = '${{ needs.test-check.result }}';
            const buildResult = '${{ needs.build-check.result }}';
            
            const statusEmoji = {
              'success': '✅',
              'failure': '❌',
              'cancelled': '⚠️',
              'skipped': '⏭️'
            };
            
            let summary = '## 🔍 Resultados de Validación PR\n\n';
            summary += '### Checks de Calidad\n';
            summary += `${statusEmoji[qualityResult] || '❓'} **Quality Check**: ${qualityResult}\n`;
            summary += `${statusEmoji[testResult] || '❓'} **Tests**: ${testResult}\n`;
            summary += `${statusEmoji[buildResult] || '❓'} **Build**: ${buildResult}\n\n`;
            summary += '### Detalles\n';
            summary += '• **ESLint**: Verificación de reglas de complejidad y estilo\n';
            summary += '• **jscpd**: Detección de código duplicado\n';
            summary += '• **Tests**: Ejecución de pruebas unitarias\n';
            summary += '• **Build**: Verificación de compilación\n\n';
            
            if (qualityResult === 'success' && testResult === 'success' && buildResult === 'success') {
              summary += '🎉 **¡Todos los checks pasaron correctamente!** El PR está listo para revisión.\n';
            } else {
              summary += '⚠️ **Algunos checks fallaron.** Por favor revisa los errores y corrige antes de hacer merge.\n';
            }
            
            summary += '\n---\n';
            summary += '*Este comentario se genera automáticamente por GitHub Actions*';

            // Buscar comentario anterior del bot
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('Resultados de Validación PR')
            );
            
            if (botComment) {
              // Actualizar comentario existente
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: summary
              });
            } else {
              // Crear nuevo comentario
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: summary
              });
            }